# Generated by Django 5.0.3 on 2024-04-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=60)),
                ('sobrenome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('tipo_usuario', models.PositiveSmallIntegerField(choices=[(1, 'Aluno'), (2, 'Admin')])),
            ],
        ),
    ]
