# Generated by Django 5.0.3 on 2024-05-03 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('turno', models.PositiveSmallIntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Noturno')])),
                ('calendario', models.FileField(null=True, upload_to='')),
                ('disciplinas', models.ManyToManyField(to='api.disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='turmas',
            field=models.ManyToManyField(to='api.turma'),
        ),
    ]
