# Generated by Django 5.0.3 on 2024-05-25 03:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuserdisciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Aguardando Resposta'), (2, 'Resolvido')], default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
