# Generated by Django 5.0.3 on 2024-06-02 20:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pendencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserdisciplina',
            name='nota',
        ),
        migrations.AddField(
            model_name='customuserdisciplina',
            name='notas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=3),
        ),
    ]
