# Generated by Django 5.0.3 on 2024-06-08 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customuserdisciplina_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendencias',
            name='custom_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
