# Generated by Django 5.0.3 on 2024-06-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pendencias_custom_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pendencias',
            new_name='Pendencia',
        ),
    ]
