# Generated by Django 5.0.3 on 2024-06-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_pendencias_pendencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendencia',
            name='nome',
        ),
    ]
