version: '3.9'

services:

  redis:
    image: redis/redis-stack-server:latest
    restart: always

    ports:
      - 6379:6379
      - 8001:8001

  db:
    image: postgres:16.2-alpine3.19
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ivo
      POSTGRES_PASSWORD: ivo
      POSTGRES_DB: ivo
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080