services:

  redis:
    container_name: ivo_redis_stack
    image: redis/redis-stack:latest
    restart: always

    ports:
      - 6379:6379
      - 8001:8001

  db:
    container_name: ivo_db
    image: postgres:16.2-alpine3.19
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ivo
      POSTGRES_PASSWORD: ivo
      POSTGRES_DB: ivo
    ports:
      - 5432:5432
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: ivo_db_pgadmin4
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ivo@chat.com
      PGADMIN_DEFAULT_PASSWORD: ivo
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
volumes:
  local_pgdata:
  pgadmin-data:
